
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author COLD
 */
public class Manage_student extends javax.swing.JFrame {
    New_student student = new New_student();
    Student_operations stu = new Student_operations();
    DefaultTableModel model;
    public Manage_student() {
        initComponents();
   
        stu.fill_stu_table(manage_table, "");
        model = (DefaultTableModel)manage_table.getModel();
        ButtonGroup bg = new ButtonGroup();
        bg.add(manage_male_button);
        bg.add(manage_female_button);
        manage_table.setRowHeight(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manage_male_button = new javax.swing.JRadioButton();
        manage_female_button = new javax.swing.JRadioButton();
        manage_phone_label = new javax.swing.JLabel();
        manage_phone_field = new javax.swing.JTextField();
        manage_fn_label = new javax.swing.JLabel();
        manage_delete = new javax.swing.JButton();
        manage_fn_field = new javax.swing.JTextField();
        manage_ln_label = new javax.swing.JLabel();
        manage_edit = new javax.swing.JButton();
        manage_ln_field = new javax.swing.JTextField();
        manage_gen_label = new javax.swing.JLabel();
        manage_id_field = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        manage_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        manage_table = new javax.swing.JTable();
        manage_search_lbl = new javax.swing.JLabel();
        manage_search_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manage_male_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manage_male_button.setText("Male");

        manage_female_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manage_female_button.setText("Female");

        manage_phone_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manage_phone_label.setText("Phone");

        manage_phone_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        manage_phone_field.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        manage_phone_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_phone_fieldActionPerformed(evt);
            }
        });
        manage_phone_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                manage_phone_fieldKeyTyped(evt);
            }
        });

        manage_fn_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manage_fn_label.setText("First Name");

        manage_delete.setBackground(new java.awt.Color(64, 191, 216));
        manage_delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manage_delete.setText("Delete");
        manage_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_deleteActionPerformed(evt);
            }
        });

        manage_fn_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        manage_fn_field.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        manage_fn_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_fn_fieldActionPerformed(evt);
            }
        });
        manage_fn_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                manage_fn_fieldKeyTyped(evt);
            }
        });

        manage_ln_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manage_ln_label.setText("Last Name");

        manage_edit.setBackground(new java.awt.Color(64, 191, 216));
        manage_edit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manage_edit.setText("Edit");
        manage_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_editActionPerformed(evt);
            }
        });

        manage_ln_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        manage_ln_field.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        manage_ln_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_ln_fieldActionPerformed(evt);
            }
        });
        manage_ln_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                manage_ln_fieldKeyTyped(evt);
            }
        });

        manage_gen_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manage_gen_label.setText("Gender");

        manage_id_field.setEditable(false);
        manage_id_field.setBackground(new java.awt.Color(255, 255, 255));
        manage_id_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        manage_id_field.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        manage_id_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_id_fieldActionPerformed(evt);
            }
        });
        manage_id_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                manage_id_fieldKeyTyped(evt);
            }
        });

        id_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id_label.setText("ID");

        manage_add.setBackground(new java.awt.Color(64, 191, 216));
        manage_add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manage_add.setText("Add");
        manage_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_addActionPerformed(evt);
            }
        });

        manage_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Gender", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        manage_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manage_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(manage_table);

        manage_search_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manage_search_lbl.setForeground(new java.awt.Color(255, 102, 102));
        manage_search_lbl.setText("Search");

        manage_search_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        manage_search_field.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        manage_search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_search_fieldActionPerformed(evt);
            }
        });
        manage_search_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manage_search_fieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                manage_search_fieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                manage_search_fieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manage_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manage_add, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manage_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manage_gen_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(manage_male_button)
                        .addGap(18, 18, 18)
                        .addComponent(manage_female_button))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(manage_phone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(manage_phone_field))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(manage_ln_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(manage_ln_field))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(manage_fn_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(manage_fn_field, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manage_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manage_search_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manage_search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manage_search_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manage_search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manage_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manage_fn_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manage_fn_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manage_ln_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manage_ln_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manage_gen_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manage_male_button)
                            .addComponent(manage_female_button))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manage_phone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manage_phone_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manage_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manage_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manage_add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manage_phone_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_phone_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_phone_fieldActionPerformed

    private void manage_phone_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manage_phone_fieldKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_manage_phone_fieldKeyTyped

    private void manage_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_deleteActionPerformed
        
        if(manage_id_field.getText().equals("")){
        
        JOptionPane.showMessageDialog(null,"No Student is Selected","No Selection", JOptionPane.ERROR_MESSAGE);
        }
        else{
        
        int id = Integer.valueOf(manage_id_field.getText());
        stu.operations(3, id, null, null, null, null);}
        
        stu.fill_stu_table(manage_table, "");
        manage_table.setModel(new DefaultTableModel(null, new Object[]{"ID","First Name", "Last Name", "Gender", "Phone"}));
        stu.fill_stu_table(manage_table,manage_search_field.getText());
        Stats.n_stu.setText(Integer.toString(MyFunction.data_count("student")));
        
        manage_id_field.setText("");
        manage_fn_field.setText("");
        manage_ln_field.setText("");
        manage_phone_field.setText("");
        manage_female_button.setSelected(false);
        manage_male_button.setSelected(false);
      
    }//GEN-LAST:event_manage_deleteActionPerformed

    private void manage_fn_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_fn_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_fn_fieldActionPerformed

    private void manage_fn_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manage_fn_fieldKeyTyped
        if(!Character.isSpaceChar(evt.getKeyChar()) && !Character.isAlphabetic(evt.getKeyChar()) ){
            evt.consume();     // TODO add your handling code here:
    }//GEN-LAST:event_manage_fn_fieldKeyTyped
    }
    
    public boolean student_verify(){
    
        if(manage_fn_field.getText().equals("") ||
           manage_ln_field.getText().equals("") ||
           manage_phone_field.getText().equals("") ||
           manage_id_field.getText().equals("")){
            JOptionPane.showMessageDialog(null,"There are empty fields","Empty Fields",JOptionPane.ERROR_MESSAGE);
            
            
        return false;}
        
        else{return true;}
    
    }
    
    private void manage_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_editActionPerformed

        String f_name = manage_fn_field.getText();
        String l_name = manage_ln_field.getText();
        String phone = manage_phone_field.getText();
        int id = Integer.valueOf(manage_id_field.getText());
        String gender = "Male";
        if(manage_female_button.isSelected()){
            gender = "Female";}
//        } else if(manage_male_button.isSelected()){
//            gender = "Male";
//        }
        if(student_verify()){
            stu.operations(2, id, f_name, l_name, gender, phone);
            
            Manage_student.manage_table.setModel(new DefaultTableModel(null,new Object[]{"ID","First Name", "Last Name", "Gender", "Phone"}));
            stu.fill_stu_table(Manage_student.manage_table, "");

        }

    }//GEN-LAST:event_manage_editActionPerformed
    
    private void manage_ln_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_ln_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_ln_fieldActionPerformed

    private void manage_ln_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manage_ln_fieldKeyTyped
        if(!Character.isSpaceChar(evt.getKeyChar()) && !Character.isAlphabetic(evt.getKeyChar()) ){
            evt.consume();
    }//GEN-LAST:event_manage_ln_fieldKeyTyped
    }
    private void manage_id_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_id_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_id_fieldActionPerformed

    private void manage_id_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manage_id_fieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_id_fieldKeyTyped

    private void manage_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_addActionPerformed
                student.setVisible(true);
                student.pack();
                student.setLocationRelativeTo(null);
                student.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_manage_addActionPerformed

    private void manage_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_tableMouseClicked

        int table_index = manage_table.getSelectedRow();
        manage_female_button.setSelected(false);
        manage_male_button.setSelected(true);
        
        DefaultTableModel model = (DefaultTableModel)manage_table.getModel();
        
        manage_id_field.setText(model.getValueAt(table_index, 0).toString());
        manage_fn_field.setText(model.getValueAt(table_index, 1).toString());
        manage_ln_field.setText(model.getValueAt(table_index, 2).toString());
        manage_phone_field.setText(model.getValueAt(table_index, 4).toString());

        if(model.getValueAt(table_index, 3).toString().equals("Female")){
        manage_female_button.setSelected(true);
        } else{manage_male_button.setSelected(true);}
    }//GEN-LAST:event_manage_tableMouseClicked

    private void manage_search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_search_fieldActionPerformed

    private void manage_search_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manage_search_fieldKeyTyped

    }//GEN-LAST:event_manage_search_fieldKeyTyped

    private void manage_search_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manage_search_fieldKeyPressed
        
       
    }//GEN-LAST:event_manage_search_fieldKeyPressed

    private void manage_search_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manage_search_fieldKeyReleased
        
       manage_table.setModel(new DefaultTableModel(null, new Object[]{"ID","First Name", "Last Name", "Gender", "Phone"}));
       stu.fill_stu_table(manage_table,manage_search_field.getText());
    }//GEN-LAST:event_manage_search_fieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manage_add;
    private javax.swing.JButton manage_delete;
    private javax.swing.JButton manage_edit;
    private javax.swing.JRadioButton manage_female_button;
    private javax.swing.JTextField manage_fn_field;
    private javax.swing.JLabel manage_fn_label;
    private javax.swing.JLabel manage_gen_label;
    private javax.swing.JTextField manage_id_field;
    private javax.swing.JTextField manage_ln_field;
    private javax.swing.JLabel manage_ln_label;
    private javax.swing.JRadioButton manage_male_button;
    private javax.swing.JTextField manage_phone_field;
    private javax.swing.JLabel manage_phone_label;
    private javax.swing.JTextField manage_search_field;
    private javax.swing.JLabel manage_search_lbl;
    public static javax.swing.JTable manage_table;
    // End of variables declaration//GEN-END:variables
}
