
import javax.swing.table.DefaultTableModel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author COLD
 */
public class Marks_manage extends javax.swing.JFrame {
    
    Marks_operations mo = new Marks_operations();
    Marks m = new Marks();
    
    public Marks_manage() {
        initComponents();
        mo.fill_marks_table(marks_manage_table);
        marks_manage_table.setRowHeight(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marks_stu_id = new javax.swing.JTextField();
        remove = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        course_edit = new javax.swing.JButton();
        course_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        marks_manage_table = new javax.swing.JTable();
        marks_field = new javax.swing.JTextField();
        marks_lbl = new javax.swing.JLabel();
        stu_lbl = new javax.swing.JLabel();
        marks_course_id = new javax.swing.JTextField();
        Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        marks_stu_id.setEditable(false);
        marks_stu_id.setBackground(new java.awt.Color(255, 255, 255));
        marks_stu_id.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        marks_stu_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        marks_stu_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks_stu_idActionPerformed(evt);
            }
        });
        marks_stu_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                marks_stu_idKeyTyped(evt);
            }
        });

        remove.setBackground(new java.awt.Color(64, 191, 216));
        remove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        remove.setText("Delete");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        course_edit.setBackground(new java.awt.Color(64, 191, 216));
        course_edit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        course_edit.setText("Edit");
        course_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_editActionPerformed(evt);
            }
        });

        course_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        course_lbl.setText("Course ID");

        marks_manage_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Course ID", "Marks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        marks_manage_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marks_manage_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(marks_manage_table);

        marks_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        marks_field.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        marks_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks_fieldActionPerformed(evt);
            }
        });
        marks_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                marks_fieldKeyTyped(evt);
            }
        });

        marks_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        marks_lbl.setText("Marks");

        stu_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stu_lbl.setText("Student ID");

        marks_course_id.setEditable(false);
        marks_course_id.setBackground(new java.awt.Color(255, 255, 255));
        marks_course_id.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        marks_course_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        marks_course_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks_course_idActionPerformed(evt);
            }
        });
        marks_course_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                marks_course_idKeyTyped(evt);
            }
        });

        Add.setBackground(new java.awt.Color(64, 191, 216));
        Add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stu_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(marks_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marks_field, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(course_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(marks_course_id, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(marks_stu_id, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(course_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stu_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marks_stu_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marks_course_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marks_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marks_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marks_stu_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks_stu_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks_stu_idActionPerformed

    private void marks_stu_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marks_stu_idKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_marks_stu_idKeyTyped

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed

        int student_id = Integer.valueOf(marks_stu_id.getText());
        int course_id = Integer.valueOf(marks_course_id.getText());
        
        mo.operations(3, student_id, course_id, null);
        marks_manage_table.setModel(new DefaultTableModel(null,new Object[]{"Student ID","Course ID","Marks"}));
        mo.fill_marks_table(marks_manage_table);
        
    }//GEN-LAST:event_removeActionPerformed

    private void course_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_editActionPerformed

        int student_id = Integer.valueOf(marks_stu_id.getText());
        int course_id = Integer.valueOf(marks_course_id.getText());
        int marks = Integer.valueOf(marks_field.getText());
        
        mo.operations(2, student_id, course_id, marks);
         marks_manage_table.setModel(new DefaultTableModel(null,new Object[]{"Student ID","Course ID","Marks"}));
         
        mo.fill_marks_table(marks_manage_table);

//        String course_name = mid_field.getText();
        //        if(!co.course_existed(mid_field.getText())){
            //            int id = Integer.valueOf(marks_stu_id.getText());
            //            int hours = Integer.valueOf(course_spinner.getValue().toString());
            //            co.operations(2,id, course_name, hours);
            //            Manage_course.course_table.setModel(new DefaultTableModel(null,new Object[]{"Course ID","Course Name","Course hours"}));
            //            co.fill_course_table(Manage_course.course_table);
            //            JOptionPane.showMessageDialog(null,course_name+" has been edited");
            //        }
        //        else{
            //            JOptionPane.showMessageDialog(null,course_name+" is already existed ","Course Existed",JOptionPane.ERROR_MESSAGE);
            //        }
    }//GEN-LAST:event_course_editActionPerformed

    private void marks_manage_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marks_manage_tableMouseClicked

        int table_index = marks_manage_table.getSelectedRow();
        marks_stu_id.setText(marks_manage_table.getValueAt(table_index, 0).toString());
        marks_course_id.setText(marks_manage_table.getValueAt(table_index, 1).toString());
        marks_field.setText(marks_manage_table.getValueAt(table_index, 2).toString());


        //        marks_stu_id.setText(marks_table.getValueAt(table_index, 0).toString());
        //        mid_field.setText(marks_table.getValueAt(table_index, 1).toString());
        //        course_spinner.setValue(Integer.valueOf(marks_table.getValueAt(table_index, 2).toString()));
    }//GEN-LAST:event_marks_manage_tableMouseClicked

    private void marks_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks_fieldActionPerformed

    private void marks_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marks_fieldKeyTyped
        //        if(!Character.isSpaceChar(evt.getKeyChar()) && !Character.isAlphabetic(evt.getKeyChar()) ){
            //            evt.consume();     // TODO add your handling code here:
    }//GEN-LAST:event_marks_fieldKeyTyped

    private void marks_course_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks_course_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks_course_idActionPerformed

    private void marks_course_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marks_course_idKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_marks_course_idKeyTyped

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(DISPOSE_ON_CLOSE);    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marks_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marks_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marks_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marks_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marks_manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton course_edit;
    private javax.swing.JLabel course_lbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField marks_course_id;
    private javax.swing.JTextField marks_field;
    private javax.swing.JLabel marks_lbl;
    public static javax.swing.JTable marks_manage_table;
    private javax.swing.JTextField marks_stu_id;
    private javax.swing.JButton remove;
    private javax.swing.JLabel stu_lbl;
    // End of variables declaration//GEN-END:variables
}
